spring:
  application:
    name: shorturl

  datasource:
    url: jdbc:postgresql://localhost:5432/shorturldb
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  web:
    error:
      include-stacktrace: never

server:
  port: 8081
logging:
  file:
    name: logs/application.log

